name: Deploy

on:
  - push
#  push:
#    branches:
#      - master

jobs:
  deploy:
    name: "GitHub Pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Generate public directory
        run: yarn export
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
